# Generated by Django 5.2.5 on 2025-09-08 17:18

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Numero de telefone', max_length=15, verbose_name='Fone')),
                ('email', models.EmailField(help_text='E-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
                ('funcao', models.CharField(help_text='Função na empresa', max_length=35, verbose_name='Função')),
                ('data_admissao', models.CharField(help_text='Data de admissão na empresa', verbose_name='Admissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
