# Generated by Django 5.2.5 on 2025-08-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do fornecedor', max_length=70, verbose_name='Nome')),
                ('cnpj', models.CharField(help_text='CNPJ do fornecedor', max_length=18, verbose_name='CNPJ')),
                ('fone', models.CharField(help_text='Fone do fornecedor', max_length=20, verbose_name='Fone')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
