# Generated by Django 5.2.5 on 2025-09-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedores',
            new_name='Fornecedor',
        ),
    ]
