# Generated by Django 5.2.5 on 2025-09-10 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('funcionarios', '0001_initial'),
        ('servicos', '0004_servico_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('A', 'Agendado'), ('B', 'Realizado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Situação')),
                ('observacoes', models.TextField(blank=True, max_length=300, null=True, verbose_name='Observações')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do serviço', max_digits=6, verbose_name='Preço')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamento', to='agendamentos.agendamento', verbose_name='Agendamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionario', to='funcionarios.funcionario', verbose_name='Funcionario')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordem_servico', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Serviço realizado',
                'verbose_name_plural': 'Serviços realizados',
                'constraints': [models.UniqueConstraint(fields=('agendamento', 'servico'), name='constraint_agendamento')],
            },
        ),
    ]
