# Generated by Django 5.2.5 on 2025-09-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_ordemservicos'),
        ('servicos', '0004_servico_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(through='agendamentos.OrdemServicos', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
