# Generated by Django 5.2.5 on 2025-09-11 17:07

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': [django.db.models.functions.text.Upper('nome')], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(default='A', help_text='Status do agendamento', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='ordemservicos',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='agendamentos.agendamento', verbose_name='Agendamento'),
        ),
    ]
