# Generated by Django 5.2.5 on 2025-09-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_agendamento_options_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-horario'], 'permissions': (('fechar_agendamento', 'Permite fazer o fechamento de um agendamento'),), 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
