# Generated by Django 5.2.5 on 2025-09-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade utilizada de produto', max_digits=5, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(help_text='Nome do produto utilizado', on_delete=django.db.models.deletion.PROTECT, related_name='produto', to='produtos.produto', verbose_name='Produto')),
                ('servico', models.ForeignKey(help_text='Nome do serviço realizado', on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='servicos.servico', verbose_name='Serviço')),
            ],
        ),
    ]
