# Generated by Django 5.2.5 on 2025-09-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0002_produtoservico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutoServico',
            new_name='ProdutosServico',
        ),
    ]
