# Generated by Django 5.2.5 on 2025-09-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0003_rename_produtoservico_produtosservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produto',
            field=models.ManyToManyField(through='servicos.ProdutosServico', to='produtos.produto'),
        ),
    ]
