# Generated by Django 5.2.5 on 2025-09-11 17:07

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_servico_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': [django.db.models.functions.text.Upper('nome')]},
        ),
    ]
